### ISSUE TITLE
Downloader release v1.4.0 banner states DEVELOPMENT

### ISSUE THREAD

**Issue by dennishendriksen** [molgenis/molgenis-tools-emx-downloader#86]
# How to Reproduce
- Download and run https://registry.molgenis.org/repository/maven-releases/org/molgenis/downloader/1.4.0/downloader-1.4.0.jar

# Expected
```
--------------
<banner>
Version: 1.4.0
--------------
```

# Observed
```
--------------
<banner>
Version: DEVELOPMENT
--------------
```

**Comment by dennishendriksen** [comment]
Magic happens here: https://github.com/molgenis/molgenis-tools-emx-downloader/blame/master/src/main/java/org/molgenis/downloader/Downloader.java#L80

Any thoughts @fdlk ?

**Comment by fdlk** [comment]
I think I broke this when I moved the build to Jenkins. Taking a quick look..
